<?xml version="1.0" encoding="UTF-8"?>
<definitions name="recrutingWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/WSDLUtilidad/recrutingWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/java/recrutingWSDL" xmlns:ns="http://xml.netbeans.org/schema/recrutingXmlSchema" xmlns:tns1="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/WSDLUtilidad/recrutingWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/WSDLUtilidad/recrutingWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/recrutingXmlSchema" schemaLocation="../Utilidad/recrutingXmlSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="recrutingWSDLOperationRequest">
        <part name="part1" element="ns:numberPeople"/>
    </message>
    <message name="recrutingWSDLOperationResponse">
        <part name="part1" element="ns:recrutedPeople"/>
    </message>
    <portType name="recrutingWSDLPortType">
        <operation name="recrutingWSDLOperation">
            <input name="input1" message="tns1:recrutingWSDLOperationRequest"/>
            <output name="output1" message="tns1:recrutingWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="recrutingWSDLBinding" type="tns1:recrutingWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="recrutingWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="recrutingWSDLService">
        <port name="recrutingWSDLPort" binding="tns1:recrutingWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/recrutingWSDLService/recrutingWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="recrutingWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="recrutingWSDLPortTypeRole" portType="tns1:recrutingWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
