<?xml version="1.0" encoding="UTF-8"?>
<definitions name="isActiveWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/java/isActiveWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/java/isActiveWSDL" xmlns:ns="http://xml.netbeans.org/schema/isActiveXmlSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/JavaTestWebServices2/java/isActiveWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/isActiveXmlSchema" schemaLocation="../Utilidad/isActiveXmlSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="isActiveWSDLOperationRequest">
        <part name="idClient" element="ns:idClient"/>
    </message>
    <message name="isActiveWSDLOperationResponse">
        <part name="active" element="ns:isActive"/>
    </message>
    <portType name="isActiveWSDLPortType">
        <operation name="isActiveWSDLOperation">
            <input name="input1" message="tns:isActiveWSDLOperationRequest"/>
            <output name="output1" message="tns:isActiveWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="isActiveWSDLBinding" type="tns:isActiveWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="isActiveWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="isActiveWSDLService">
        <port name="isActiveWSDLPort" binding="tns:isActiveWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/isActiveWSDLService/isActiveWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="isActiveWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="isActiveWSDLPortTypeRole" portType="tns:isActiveWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
